services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-teamfinder}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teamfinder}
      POSTGRES_DB: ${POSTGRES_DB:-teamfinder_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER:-teamfinder}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-teamfinder}
      - DB_NAME=${POSTGRES_DB:-teamfinder_db}
      - DB_PORT=5432
      - BASIC_SERVER_PORT=8090

      # .env FILE:
      - TG_BOT_TOKEN=AAGF4AIILsB8-DBsqf7m7D3vJXbT3lxOD2k
      - TG_BOT_ID=7072997582
      - EMAIL_LOGIN=teamfinderverifycode@gmail.com
      - EMAIL_PASSWORD=eslkvkemwvomfdokvmnwroiptunvjfwnhptw
      - DATABASE_URL=postgres://teamfinder:teamfinder@localhost:5432/teamfinder_db?sslmode=disable
      - POSTGRES_USER=teamfinder
      - POSTGRES_PASSWORD=teamfinder
      - POSTGRES_DB=teamfinder_db

      
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8090

    depends_on:
      - backend

volumes:
  postgres_data:
