services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - teamfinder_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BASIC_SERVER_PORT}:${BASIC_SERVER_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GO_ENV=production
      - BASIC_SERVER_PORT=${BASIC_SERVER_PORT}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_BOT_ID=${TG_BOT_ID}
      - EMAIL_LOGIN=${EMAIL_LOGIN}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - teamfinder_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - teamfinder_net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./teamfinder.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - teamfinder_net

volumes:
  postgres_data:

networks:
  teamfinder_net:
    driver: bridge